# Generated by Django 5.2.1 on 2025-06-02 15:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the company.", max_length=255, unique=True
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SMALL", "1-50 employees"),
                            ("MEDIUM", "51-250 employees"),
                            ("LARGE", "251-1000 employees"),
                            ("ENTERPRISE", "1000+ employees"),
                        ],
                        help_text="Size of the company based on employee count.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Company's official website URL.",
                        null=True,
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        help_text="Company's LinkedIn profile URL.",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Primary location of the company.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("REVIEW", "Under Review"),
                            ("SELECTED", "Selected"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NEW",
                        help_text="Current status of the candidate within the hiring process.",
                        max_length=20,
                    ),
                ),
                (
                    "last_status_update",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp of the last status change.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                (
                    "resume_file_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company associated with this candidate.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="beta_1.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("company", "email")},
            },
        ),
        migrations.CreateModel(
            name="CandidateStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "New"),
                            ("REVIEW", "Under Review"),
                            ("SELECTED", "Selected"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("REVIEW", "Under Review"),
                            ("SELECTED", "Selected"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="beta_1.candidate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_status_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("REGISTER", "User Registration"),
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("RESUME_UPLOAD", "Resume Upload"),
                            ("JD_SEARCH", "Job Description Search"),
                            ("LINKEDIN_SEARCH", "LinkedIn Search"),
                            ("PROFILE_SCRAPE", "LinkedIn Profile Scrape"),
                            ("PROFILE_ANALYZE", "Profile Analysis"),
                            ("CANDIDATE_STATUS_UPDATE", "Candidate Status Update"),
                            ("JD_SEARCH_ERROR", "JD Search Error"),
                            ("PROFILE_SCRAPE_ERROR", "Profile Scrape Error"),
                            ("LINKEDIN_SEARCH_ERROR", "LinkedIn Search Error"),
                            ("RESUME_UPLOAD_ERROR", "Resume Upload Error"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("details_json", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs_by_company",
                        to="beta_1.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="beta_1.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HRProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this HR user belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hr_users",
                        to="beta_1.company",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Django User associated with this HR profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkedInProfile",
            fields=[
                (
                    "linkedin_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("snippet", models.TextField()),
                ("position", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("search_query", models.TextField()),
                ("job_description_for_search", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linkedin_search_results",
                        to="beta_1.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LinkedIn Profiles (Search Results)",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="beta_1.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AISummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_description_hash", models.CharField(max_length=128)),
                ("summary_text", models.TextField()),
                ("score", models.FloatField(blank=True, null=True)),
                ("details_json", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_summaries",
                        to="beta_1.candidate",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_summaries_by_company",
                        to="beta_1.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "AI Summaries",
                "unique_together": {("candidate", "job_description_hash", "company")},
            },
        ),
        migrations.CreateModel(
            name="CandidateSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("years_of_experience", models.FloatField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beta_1.candidate",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="beta_1.skill"
                    ),
                ),
            ],
            options={
                "unique_together": {("candidate", "skill")},
            },
        ),
    ]
