# Generated by Django 5.2.1 on 2025-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beta_1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-50", "1-50 employees"),
                    ("51-250", "51-250 employees"),
                    ("251-1000", "251-1000 employees"),
                    ("1000+", "1000+ employees"),
                ],
                help_text="Size of the company based on employee count.",
                max_length=50,
                null=True,
            ),
        ),
    ]
